/**:
    ros__parameters:
        image_transport: raw    # image format
        family: 16h5           # tag family name
        size: 0.0375             # tag edge size in meter
        max_hamming: 0          # maximum allowed hamming distance (corrected bits)
        qos_profile: default    # optional qos_profile, "sensor_data", "default", or "system_default"

        # see "apriltag.h" 'struct apriltag_detector' for more documentation on these optional parameters
        detector:
            threads: 1          # number of threads
            decimate: 2.0       # decimate resolution for quad detection
            blur: 0.0           # sigma of Gaussian blur for quad detection
            refine: True        # snap to strong gradients
            sharpening: 0.25    # sharpening of decoded images
            debug: False        # write additional debugging images to current working directory


        pose_estimation_method: "pnp"   # method for estimating the tag pose

        # optional list of tags
        tag:
            ids: [1, 2, 3, 4]            # tag ID
            frames: [tag_1, tag_2, tag_3, tag_4]  # optional frame name
            sizes: [0.0375, 0.0375, 0.0375, 0.0375]   # optional tag-specific edge size
